<h1>promise.catch</h1> <p>The <strong>catch()</strong> method returns a <code>Promise</code> and deals with rejected cases only. It behaves the same as calling <a href="then"><code>Promise.prototype.then(undefined, onRejected)</code></a> (in fact, calling <code>obj.catch(onRejected)</code> internally calls <code>obj.then(undefined, onRejected)</code>). This means, that you have to provide <code>onRejected</code> function even if you want to fallback to <code>undefined</code> result value - for example <code>obj.catch(() =&gt; {})</code>.</p> <iframe src="https://interactive-examples.mdn.mozilla.net/pages/js/promise-catch.html" frameborder="0" width="100%" class="interactive interactive-js" height="250"></iframe>    <h2 id="Syntax">Syntax</h2> <pre class="syntaxbox"><var>p.catch(onRejected)</var>;

p.catch(function(reason) {
   // rejection
});
</pre> <h3 id="Parameters">Parameters</h3> <dl> <dt>onRejected</dt> <dd>A <a href="../function"><code>Function</code></a> called when the <code>Promise</code> is rejected. This function has one argument: <dl> <dt><code>reason</code></dt> <dd>The rejection reason.</dd> </dl> The Promise returned by <code>catch()</code> is rejected if <code>onRejected</code> throws an error or returns a Promise which is itself rejected; otherwise, it is resolved.</dd> </dl> <h3 id="Return_value">Return value</h3> <p>Internally calls <code>Promise.prototype.then</code> on the object upon which is called, passing the parameters <code>undefined</code> and the <code>onRejected</code> handler received; then returns the value of that call (which is a <a href="../promise"><code>Promise</code></a>).</p> <div class="warning"> <p>The examples below are throwing strings. This is considered bad practice. Always throw an instance of <a href="../error">Error</a>. Otherwise the part doing the catching would have to make checks to see if the argument was a string or an error, and you might lose valuable information like stack traces</p> </div> <p><strong>Demonstration of the internal call:</strong></p> <pre data-language="js">// overriding original Promise.prototype.then/catch just to add some logs
(function(Promise){
    var originalThen = Promise.prototype.then;
    var originalCatch = Promise.prototype.catch;
    
    Promise.prototype.then = function(){
        console.log('&gt; &gt; &gt; &gt; &gt; &gt; called .then on %o with arguments: %o', this, arguments);
        return originalThen.apply(this, arguments);
    };
    Promise.prototype.catch = function(){
        console.log('&gt; &gt; &gt; &gt; &gt; &gt; called .catch on %o with arguments: %o', this, arguments);
        return originalCatch.apply(this, arguments);
    };

})(this.Promise);



// calling catch on an already resolved promise
Promise.resolve().catch(function XXX(){});

// logs:
// &gt; &gt; &gt; &gt; &gt; &gt; called .catch on Promise{} with arguments: Arguments{1} [0: function XXX()]
// &gt; &gt; &gt; &gt; &gt; &gt; called .then on Promise{} with arguments: Arguments{2} [0: undefined, 1: function XXX()]
</pre> <h2 id="Description">Description</h2> <p>The <code>catch</code> method can be useful for error handling in your promise composition.</p> <h2 id="Examples">Examples</h2> <h3 id="Using_and_chaining_the_catch_method">Using and chaining the <code>catch</code> method</h3> <pre data-language="js">var p1 = new Promise(function(resolve, reject) {
  resolve('Success');
});

p1.then(function(value) {
  console.log(value); // "Success!"
  throw 'oh, no!';
}).catch(function(e) {
  console.log(e); // "oh, no!"
}).then(function(){
  console.log('after a catch the chain is restored');
}, function () {
  console.log('Not fired due to the catch');
});

// The following behaves the same as above
p1.then(function(value) {
  console.log(value); // "Success!"
  return Promise.reject('oh, no!');
}).catch(function(e) {
  console.log(e); // "oh, no!"
}).then(function(){
  console.log('after a catch the chain is restored');
}, function () {
  console.log('Not fired due to the catch');
});
</pre> <h3 id="Gotchas_when_throwing_errors">Gotchas when throwing errors</h3> <pre data-language="js">// Throwing an error will call the catch method most of the time
var p1 = new Promise(function(resolve, reject) {
  throw 'Uh-oh!';
});

p1.catch(function(e) {
  console.log(e); // "Uh-oh!"
});

// Errors thrown inside asynchronous functions will act like uncaught errors
var p2 = new Promise(function(resolve, reject) {
  setTimeout(function() {
    throw 'Uncaught Exception!';
  }, 1000);
});

p2.catch(function(e) {
  console.log(e); // This is never called
});

// Errors thrown after resolve is called will be silenced
var p3 = new Promise(function(resolve, reject) {
  resolve();
  throw 'Silenced Exception!';
});

p3.catch(function(e) {
   console.log(e); // This is never called
});</pre> <h3 id="If_it_is_resolved">If it is resolved</h3> <pre data-language="js">//Create a promise which would not call onReject
var p1 = Promise.resolve("calling next");

var p2 = p1.catch(function (reason) {
    //This is never called
    console.log("catch p1!");
    console.log(reason);
});

p2.then(function (value) {
    console.log("next promise's onFulfilled"); /* next promise's onFulfilled */
    console.log(value); /* calling next */
}, function (reason) {
    console.log("next promise's onRejected");
    console.log(reason);
});</pre> <h2 id="Specifications">Specifications</h2> <div class="_table"><table class="standard-table"> <tbody> <tr> <th scope="col">Specification</th> <th scope="col">Status</th> <th scope="col">Comment</th> </tr> <tr> <td><a href="https://www.ecma-international.org/ecma-262/6.0/#sec-promise.prototype.catch" hreflang="en">ECMAScript 2015 (6th Edition, ECMA-262)<br><small>The definition of 'Promise.prototype.catch' in that specification.</small></a></td> <td><span class="spec-Standard">Standard</span></td> <td>Initial definition in an ECMA standard.</td> </tr> <tr> <td><a href="https://tc39.github.io/ecma262/#sec-promise.prototype.catch" hreflang="en">ECMAScript Latest Draft (ECMA-262)<br><small>The definition of 'Promise.prototype.catch' in that specification.</small></a></td> <td><span class="spec-Draft">Draft</span></td> <td> </td> </tr> </tbody> </table></div> <h2 id="Browser_compatibility">Browser compatibility<a href="https://github.com/mdn/browser-compat-data" class="bc-github-link">Update compatibility data on GitHub</a>
</h2>  <div class="_table">
<table class="bc-table bc-table-js">
<thead>
<tr class="bc-platforms">
<th></th>
<th colspan="6">Desktop</th>
</tr>
<tr class="bc-browsers">
<th></th>
<th>Chrome</th>
<th>Edge</th>
<th>Firefox</th>
<th>Internet Explorer</th>
<th>Opera</th>
<th>Safari</th>
</tr>
</thead>
<tbody><tr>
<th scope="row">Basic support</th>
<td class="bc-supports-yes"> 32</td>
<td class="bc-supports-yes"> Yes</td>
<td class="bc-supports-yes"> 29</td>
<td class="bc-supports-no"> No</td>
<td class="bc-supports-yes"> 19</td>
<td class="bc-supports-yes"> 8</td>
</tr></tbody>
</table>
<table class="bc-table bc-table-js">
<thead>
<tr class="bc-platforms">
<th></th>
<th colspan="7">Mobile</th>
</tr>
<tr class="bc-browsers">
<th></th>
<th>Android webview</th>
<th>Chrome for Android</th>
<th>Edge Mobile</th>
<th>Firefox for Android</th>
<th>Opera for Android</th>
<th>iOS Safari</th>
<th>Samsung Internet</th>
</tr>
</thead>
<tbody><tr>
<th scope="row">Basic support</th>
<td class="bc-supports-yes"> 4.4.3</td>
<td class="bc-supports-yes"> 32</td>
<td class="bc-supports-yes"> Yes</td>
<td class="bc-supports-yes"> 29</td>
<td class="bc-supports-yes"> Yes</td>
<td class="bc-supports-yes"> 8</td>
<td class="bc-supports-yes"> Yes</td>
</tr></tbody>
</table>
<table class="bc-table bc-table-js">
<thead>
<tr class="bc-platforms">
<th></th>
<th colspan="1">Server</th>
</tr>
<tr class="bc-browsers">
<th></th>
<th>Node.js</th>
</tr>
</thead>
<tbody><tr>
<th scope="row">Basic support</th>
<td class="bc-supports-yes"> 0.12</td>
</tr></tbody>
</table>
</div> <h2 id="See_also">See also</h2> <ul> <li><a href="../promise"><code>Promise</code></a></li> <li><a href="then"><code>Promise.prototype.then()</code></a></li> </ul><div class="_attribution">
  <p class="_attribution-p">
    <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/catch$edit" class="_attribution-link">Edit this page on MDN</a>
  </p>
</div>
<div class="_attribution">
  <p class="_attribution-p">
    &copy; 2005&ndash;2018 Mozilla Developer Network and individual contributors.<br>Licensed under the Creative Commons Attribution-ShareAlike License v2.5 or later.<br>
    <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/catch" class="_attribution-link">https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/catch</a>
  </p>
</div>
